#!/usr/bin/env bash
set -eu

interface=wlp58s0
[[ -z "$interface" ]] && echo "Error: network interface not defined" && exit 1

scan_results="/var/tmp/scan_results.txt"

function extract_info {
  while read line;
  do
    if [[ "$line" =~ signal: ]]
    then
      signal=${line#signal: }
    elif [[ "$line" =~ SSID: ]]
    then
      ssid=${line#SSID: }
      printf '%3s  %-30s\n' "$signal" "'$ssid'"
    fi
  done
}

function extract_ssid {
  if [[ "$1" =~ ^[0-9]$ ]]
  then
    grep -E "^$1\).*" 
  else
    grep -i "$1" 
  fi < "$scan_results" | awk -F "'" '{ print $2 }'
}

function find_wpa_net_id {
  if [[ "$1" =~ ^[0-9]$ ]]
  then
    find_wpa_net_id $(extract_ssid $1)
  else
    local ssid="$*"
    wpa_cli -i "$interface" list_networks |
      tail -n +2 |
      grep -i "$ssid" |
      awk '{ print $1 }' |
      head -n 1
  fi
}

function usage {
  echo "Usage:"
  echo "  wpa_select l"
  echo "    List available networks"
  echo "  wpa_select c [ID, SSID]"
  echo "    Connect to network by ID/SSID"
  echo "  wpa_select a [ID]"
  echo "    Add network by ID"
}

function print_status {
  if [[ "$1" = 0 ]]
  then
    printf "\e[32m%s\e[39m\n" "OK"
    exit 0
  else
    printf "\e[31m%s\e[39m\n" "FAIL"
    exit 1
  fi
}

case "$1" in
  t) find_wpa_net_id "$2"
     ;;
  l)
    iw dev "$interface" scan |
      grep -E 'SSID:|signal' |
      extract_info |
      sort |
      awk '{ printf("%s) %20s\n", NR, $0); }' |
      tee "$scan_results"

    exit 0
    ;;
  c)
    id=$(find_wpa_net_id "$2")
    ssid=$(extract_ssid "$2")

    if [ -n "$id" ]
    then
      echo -n "Connecting to $ssid..."
      wpa_cli -i "$interface" enable_network "$id" | grep OK > /dev/null &&
      wpa_cli -i "$interface" select_network "$id" | grep OK > /dev/null

      print_status $?
      exit $?
    else
      echo "Access point not configured. Add new entry? (y/n)"
      read -p '' res

      if [[ "$res" = y ]]
      then
      	wpa_select a "$2"
      else
      	exit 0
      fi
    fi
    ;;
  a)
    ssid=$(extract_ssid "$2")
    read  -p 'psk: ' psk
    id=$(wpa_cli -i "$interface" add_network)

    echo -n "Adding $ssid..."
    wpa_cli -i "$interface" set_network "$id" ssid "\"$ssid\"" | 
      grep OK > /dev/null &&
      wpa_cli -i "$interface" set_network "$id" psk "\"$psk\"" |
      grep OK > /dev/null &&
      wpa_cli -i "$interface" save_config | grep OK > /dev/null

    print_status $?
    exit $?
    ;;
  h)
    usage
    ;;
  *)
    echo "Unknown command"
    echo
    usage

    exit 1
    ;;
esac
